# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-02 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20160228_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
