# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-02 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_auto_20160324_0434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='pets_allowed',
        ),
        migrations.AlterField(
            model_name='listing',
            name='summary',
            field=models.TextField(blank=True, max_length=1600),
        ),
    ]
