# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-18 23:04
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_auto_20160502_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to=b'listing_photos/%Y/%m/%d'),
        ),
    ]
