# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-29 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_auto_20160324_0434'),
        ('accounts', '0016_auto_20160126_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='starred',
            field=models.ManyToManyField(to='listings.Listing'),
        ),
    ]
